spring:
  application:
    name: pizza-inventory
  cloud:
    discovery:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    username: test
    password: test
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: queue-data
server:
  port: 8082
